[package]
name = "libeditor"
version = "0.1.0"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]
publish = false

[dependencies]
itertools = "0.7.8"
superslice = "0.1.0"

libsyntax2 = { path = "../libsyntax2" }
smol_str = { path = "../smol_str" }
assert_eq_text = { path = "../assert_eq_text" }
