[package]
name = "libeditor"
version = "0.1.0"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]
publish = false

[dependencies]
itertools = "0.7.8"
superslice = "0.1.0"
join_to_string = "0.1.1"

libsyntax2 = { path = "../libsyntax2" }

[dev-dependencies]
test_utils = { path = "../test_utils" }
