[package]
name = "expect"
version = "0.1.0"
authors = ["rust-analyzer developers"]
edition = "2018"

[lib]
doctest = false

[dependencies]
once_cell = "1"
difference = "2"
stdx = { path = "../stdx" }
