[package]
edition = "2018"
name = "ra_db"
version = "0.1.0"
authors = ["rust-analyzer developers"]

[dependencies]
salsa = "0.10.0"
relative-path = "0.4.0"
rustc-hash = "1.0"
parking_lot = "0.7.0"

ra_arena = { path = "../ra_arena" }
ra_syntax = { path = "../ra_syntax" }
test_utils = { path = "../test_utils" }
