[package]
edition = "2018"
name = "ra_db"
version = "0.1.0"
authors = ["rust-analyzer developers"]

[dependencies]
salsa = "0.12.3"
relative-path = "0.4.0"
rustc-hash = "1.0"

ra_syntax = { path = "../ra_syntax" }
ra_prof = { path = "../ra_prof" }
