[package]
edition = "2018"
name = "ra_db"
version = "0.1.0"
authors = ["rust-analyzer developers"]
license = "MIT OR Apache-2.0"

[lib]
doctest = false

[dependencies]
salsa = "0.15.2"
rustc-hash = "1.1.0"

ra_syntax = { path = "../ra_syntax" }
ra_cfg = { path = "../ra_cfg" }
profile = { path = "../profile" }
ra_tt = { path = "../ra_tt" }
test_utils = { path = "../test_utils" }
vfs = { path = "../vfs" }
stdx = { path = "../stdx" }
