[package]
edition = "2018"
name = "ra_ide_api"
version = "0.1.0"
authors = ["rust-analyzer deverlopers"]

[dependencies]
itertools = "0.8.0"
join_to_string = "0.1.3"
log = "0.4.5"
relative-path = "0.4.0"
rayon = "1.0.2"
fst = "0.3.1"
rustc-hash = "1.0"
parking_lot = "0.7.0"
unicase = "2.2.0"

jemallocator = { version = "0.1.9", optional = true }
jemalloc-ctl = { version = "0.2.0", optional = true }

ra_syntax = { path = "../ra_syntax" }
ra_ide_api_light = { path = "../ra_ide_api_light" }
ra_text_edit = { path = "../ra_text_edit" }
ra_db = { path = "../ra_db" }
hir = { path = "../ra_hir", package = "ra_hir" }
test_utils = { path = "../test_utils" }
ra_assists = { path = "../ra_assists" }

[dev-dependencies]
insta = "0.6.1"

[features]
jemalloc = [ "jemallocator", "jemalloc-ctl" ]
