[package]
edition = "2018"
name = "test_utils"
version = "0.1.0"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]

[dependencies]
difference = "2.0.0"
itertools = "0.8.0"
text_unit = "0.1.2"
serde_json = "1.0.24"
