language: rust

matrix:
  include:
    - rust: stable
      before_script:
        - rustup component add rustfmt-preview
      script:
        - cargo fmt --all -- --write-mode=diff
        - cargo test

branches:
  only:
    - staging
    - master
    - trying
