cache: cargo
before_cache:
  - find ./target/debug -type f -maxdepth 1 -delete
  - rm -fr ./target/debug/{deps,.fingerprint}/{*ra_*,*test*,*tools*,*gen_lsp*}
  - rm -f  ./target/.rustc_info.json

env:
  - CARGO_INCREMENTAL=0

matrix:
  include:
    - language: rust
      rust: beta
      script:
        - cargo gen-syntax --verify
        - cargo gen-tests --verify
        - cargo test
    # - language: rust
    #   rust: nightly
    #   before_script:
    #     - rustup component add clippy-preview
    #     - rustup component add rustfmt-preview
    #   script:
    #     - cargo fmt --all -- --check || true
    #     - cargo clippy
    - language: node_js
      node_js: node
      before_script: false
      script:
        - cd editors/code && npm ci && npm run travis

  allow_failures:
    - rust nightly

branches:
  only:
    - staging
    - master
    - trying
