language: generic
cache:
  # Cache the global cargo directory, but NOT the local `target` directory which
  # we cannot reuse anyway when the nightly changes (and it grows quite large
  # over time).
  directories:
    - /home/travis/.cargo

os:
- linux
- osx

before_script:
# macOS weirdness (https://github.com/travis-ci/travis-ci/issues/6307)
- if [[ "$TRAVIS_OS_NAME" == osx ]]; then rvm get stable; fi
# Compute the rust version we use. We do not use "language: rust" to have more control here.
- |
  if [ "$TRAVIS_EVENT_TYPE" = cron ]; then
    RUST_TOOLCHAIN=nightly
  else
    RUST_TOOLCHAIN=$(cat rust-version)
  fi
# install Rust
- curl https://build.travis-ci.org/files/rustup-init.sh -sSf | sh -s -- -y --default-toolchain "$RUST_TOOLCHAIN"
- export PATH=$HOME/.cargo/bin:$PATH
- rustc --version
# customize installation
- rustup target add i686-unknown-linux-gnu
- rustup target add i686-pc-windows-gnu
- rustup target add i686-pc-windows-msvc
- rustup component add rust-src
- cargo install xargo || echo "Skipping xargo install"

script:
- set -e
- |
  # Test and install plain miri
  cargo build --release --all-features --all-targets &&
  cargo test --release --all-features &&
  cargo install --all-features --force --path .
- |
  # get ourselves a MIR-full libstd
  xargo/build.sh &&
  export MIRI_SYSROOT=~/.xargo/HOST
- |
  # run all tests with full mir
  cargo test --release --all-features
- |
  # Test cargo integration
  (cd cargo-miri-test && ./run-test.py)

notifications:
  email:
    on_success: never
branches:
  only:
  - master
env:
  global:
  - RUST_TEST_NOCAPTURE=1
