language: rust

matrix:
  include:

    - rust: nightly-2018-01-26
      before_script:
        - rustup component add rustfmt-preview
      script:
        - cargo fmt -- --write-mode=diff

    - rust: stable
      script:
        - cargo test

branches:
  only:
    - staging
    - master
    - trying
