cache: cargo

matrix:
  include:
    - language: rust
      rust: beta
      script:
        - cargo gen-syntax --verify
        - cargo gen-tests --verify
        - cargo test
    # - language: rust
    #   rust: nightly
    #   before_script:
    #     - rustup component add clippy-preview
    #     - rustup component add rustfmt-preview
    #   script:
    #     - cargo fmt --all -- --check || true
    #     - cargo clippy
    - language: node_js
      node_js: node
      before_script: false
      script:
        - cd editors/code && npm ci && npm run travis

  allow_failures:
    - rust nightly

branches:
  only:
    - staging
    - master
    - trying
