environment:
    global:
        PROJECT_NAME: miri
    matrix:
        - TARGET: x86_64-pc-windows-msvc
          MSYS2_BITS: 64
        - TARGET: i686-pc-windows-msvc
          MSYS2_BITS: 32

# branches to build
branches:
  # whitelist
  only:
    - master

install:
    # install Rust
    - set PATH=C:\Program Files\Git\mingw64\bin;C:\msys64\mingw%MSYS2_BITS%\bin;%PATH%
    - set /p RUST_TOOLCHAIN=<rust-toolchain
    - curl -sSf -o rustup-init.exe https://win.rustup.rs/
    - rustup-init.exe -y --default-host %TARGET% --default-toolchain %RUST_TOOLCHAIN%
    - set PATH=%USERPROFILE%\.cargo\bin;%PATH%
    - rustc --version
    # customize installation
    - rustup component add rust-src
    - cargo install xargo
    # prepare a libstd with MIR (cannot use bash script, obviously)
    - cd xargo
    - set RUSTFLAGS=-Zalways-encode-mir -Zmir-emit-validate=1
    - xargo build
    - set RUSTFLAGS=
    - cd ..

build: false

test_script:
    - set RUSTFLAGS=-g
    - set RUST_BACKTRACE=1
    - cargo build --release
    - cargo test --release
    - set MIRI_SYSROOT=%USERPROFILE%\.xargo\HOST
    - cargo test --release

notifications:
    - provider: Email
      on_build_success: false
