environment:
    global:
        PROJECT_NAME: miri
    matrix:
        - TARGET: x86_64-pc-windows-msvc
          MSYS2_BITS: 64
        - TARGET: i686-pc-windows-msvc
          MSYS2_BITS: 32

# branches to build
branches:
  # whitelist
  only:
    - master

install:
    # Install Rust.
    - set PATH=C:\Program Files\Git\mingw64\bin;C:\msys64\mingw%MSYS2_BITS%\bin;%PATH%
    - set /p RUST_TOOLCHAIN=<rust-version
    - curl -sSf -o rustup-init.exe https://win.rustup.rs/
    - rustup-init.exe -y --default-host %TARGET% --default-toolchain %RUST_TOOLCHAIN%
    - set PATH=%USERPROFILE%\.cargo\bin;%PATH%
    - rustc --version
    # Customize installation.
    - rustup component add rust-src
    - cargo install xargo
    # Prepare a libstd with MIR (cannot use bash script, obviously).
    # The flags here should be kept in sync with `add_miri_default_args` in `src/lib.rs`.
    - cd xargo
    - set RUSTFLAGS=-Zalways-encode-mir -Zmir-emit-retag -Zmir-opt-level=0
    - xargo build
    - set RUSTFLAGS=
    - cd ..

build: false

test_script:
    - set RUSTFLAGS=-g
    - set RUST_BACKTRACE=1
    - cargo build --release --all-features --all-targets
    - cargo test --release --all-features
    - set MIRI_SYSROOT=%USERPROFILE%\.xargo\HOST
    - cargo test --release --all-features

notifications:
    - provider: Email
      on_build_success: false
