environment:
    global:
        PROJECT_NAME: miri
    matrix:
        - TARGET: x86_64-pc-windows-msvc
          MSYS2_BITS: 64
        - TARGET: i686-pc-windows-msvc
          MSYS2_BITS: 32

# branches to build
branches:
  # whitelist
  only:
    - master

install:
    # Install Rust.
    - set PATH=C:\Program Files\Git\mingw64\bin;C:\msys64\mingw%MSYS2_BITS%\bin;%PATH%
    - set /p RUST_TOOLCHAIN=<rust-version
    - curl -sSf -o rustup-init.exe https://win.rustup.rs/
    - rustup-init.exe -y --default-host %TARGET% --default-toolchain %RUST_TOOLCHAIN%
    - set PATH=%USERPROFILE%\.cargo\bin;%PATH%
    - rustc --version

build: false

test_script:
    - set RUST_TEST_NOCAPTURE=1
    - set RUST_BACKTRACE=1
    # Build miri
    - cargo build --release --all-features --all-targets
    # Get ourselves a MIR-full libstd, and use it henceforth
    - cargo run --release --all-features --bin cargo-miri -- miri setup
    - set MIRI_SYSROOT=%USERPROFILE%\AppData\Local\miri\miri\cache\HOST
    # Test miri
    - cargo test --release --all-features

notifications:
    - provider: Email
      on_build_success: false
