[package]
name = "clippy"
version = "0.0.1"
authors = [
	"Manish Goregaokar <manishsmail@gmail.com>",
	"Andre Bogus <bogusandre@gmail.com>"
]

[lib]
name = "clippy"
crate_type = ["dylib"]

[dev-dependencies]
compiletest_rs = "*"
