[package]
name = "libsyntax2"
version = "0.1.0"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]
license = "MIT OR Apache-2.0"

[workspace]
members = [ "tools", "cli" ]

[dependencies]
unicode-xid = "0.1.0"
text_unit = "0.1.2"
itertools = "0.7.5"

[dev-dependencies]
testutils = { path = "./tests/testutils" }
