[workspace]
members = ["xtask/", "lib/*", "crates/*"]

[profile.dev]
# We do want incremental builds, but they are broken at the moment :(
# https://github.com/rust-lang/rust/issues/85003#issuecomment-833796289
incremental = false

# Disabling debug info speeds up builds a bunch,
# and we don't rely on it for debugging that much.
debug = 0

[profile.dev.package]
# These speed up local tests.
rowan.opt-level = 3
rustc-hash.opt-level = 3
smol_str.opt-level = 3
text-size.opt-level = 3
# This speeds up `cargo xtask dist`.
miniz_oxide.opt-level = 3

[profile.release]
# We do want incremental release builds, but they are broken at the moment :(
# https://github.com/rust-lang/rust/issues/85003#issuecomment-833796289
incremental = false
debug = 0 # Set this to 1 or 2 to get more useful backtraces in debugger.

[profile.test]
incremental = false

[patch.'crates-io']
# rowan = { path = "../rowan" }

# chalk-solve = { path = "../chalk/chalk-solve" }
# chalk-ir = { path = "../chalk/chalk-ir" }
# chalk-recursive = { path = "../chalk/chalk-recursive" }

# ungrammar = { path = "../ungrammar" }

# salsa = { path = "../salsa" }
