cargo-features = ["default-run"]

[package]
authors = ["Scott Olson <scott@solson.me>"]
description = "An experimental interpreter for Rust MIR."
license = "MIT/Apache-2.0"
name = "miri"
repository = "https://github.com/solson/miri"
version = "0.1.0"
build = "build.rs"
default-run = "miri"

[[bin]]
doc = false
name = "miri"
path = "src/bin/miri.rs"

[[bin]]
doc = false
name = "cargo-miri"
path = "src/bin/cargo-miri.rs"
required-features = ["cargo_miri"]

[dependencies]
byteorder = { version = "1.1", features = ["i128"]}
cargo_metadata = { version = "0.6", optional = true }
env_logger = "0.5"
log = "0.4"

[features]
cargo_miri = ["cargo_metadata"]

[dev-dependencies]
compiletest_rs = { version = "0.3.12", features = ["tmp"] }
colored = "1.6"
