[package]
name = "rustc_smir"
version = "0.0.0"
edition = "2021"

[dependencies]
rustc_middle = { path = "../rustc_middle" }
rustc_driver = { path = "../rustc_driver" }
rustc_borrowck = { path = "../rustc_borrowck" }
rustc_interface = { path = "../rustc_interface" }
