[workspace]
members = [ "crates/*" ]

[profile.release]
incremental = true
debug = true

[patch.'crates-io']
cargo_metadata = { git = "https://github.com/matklad/cargo_metadata.git", branch = "well-typed" }
