[package]
name = "rustc_codegen_cretonne"
version = "0.1.0"
authors = ["bjorn3 <bjorn3@users.noreply.github.com>"]

[lib]
crate-type = ["dylib"]

[dependencies]
cretonne = "0.12.0"
cretonne-module = "0.12.0"
cretonne-simplejit = "0.12.0"
cretonne-faerie = "0.12.0"
