[package]
name = "libsyntax2"
version = "0.1.0"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]
license = "MIT OR Apache-2.0"

[dependencies]
unicode-xid = "0.1.0"

serde = "1.0.26"
serde_derive = "1.0.26"
file = "1.1.1"
ron = "0.1.5"

[dev-dependencies]
testutils = { path = "./tests/testutils" }
