[package]
edition = "2018"
name = "ra_hir_expand"
version = "0.1.0"
authors = ["rust-analyzer developers"]
license = "MIT OR Apache-2.0"

[lib]
doctest = false

[dependencies]
log = "0.4.8"
either = "1.5.3"
rustc-hash = "1.0.0"

arena = { path = "../arena" }
ra_db = { path = "../ra_db" }
syntax = { path = "../syntax" }
parser = { path = "../parser" }
profile = { path = "../profile" }
tt = { path = "../tt" }
mbe = { path = "../mbe" }
test_utils = { path = "../test_utils"}
