[package]
edition = "2018"
name = "ra_project_model"
version = "0.1.0"
authors = ["rust-analyzer developers"]

[dependencies]
log = "0.4.5"
rustc-hash = "1.0"
relative-path = "0.4.0"

walkdir = "2.2.7"

cargo_metadata = "0.7.0"

ra_arena = { path = "../ra_arena" }
ra_db = { path = "../ra_db" }

serde = { version = "1.0.89", features = ["derive"] }
serde_json = "1.0.39"

[dev-dependencies]
test_utils = { path = "../test_utils" }
