
[package]
name = "ra_syntax-fuzz"
version = "0.0.1"
authors = ["rust-analyzer deverlopers"]
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies.ra_syntax]
path = ".."
[dependencies.libfuzzer-sys]
git = "https://github.com/rust-fuzz/libfuzzer-sys.git"

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[[bin]]
name = "parser"
path = "fuzz_targets/parser.rs"
