[package]
name = "proc-macro-srv"
version = "0.0.0"
description = "TBD"

authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
object = { version = "0.29.0", default-features = false, features = [
    "std",
    "read_core",
    "elf",
    "macho",
    "pe",
] }
libloading = "0.7.3"
memmap2 = "0.5.4"

tt = { path = "../tt", version = "0.0.0" }
mbe = { path = "../mbe", version = "0.0.0" }
paths = { path = "../paths", version = "0.0.0" }
proc-macro-api = { path = "../proc-macro-api", version = "0.0.0" }

[dev-dependencies]
expect-test = "1.4.0"

# used as proc macro test targets
proc-macro-test = { path = "../proc-macro-test" }

[features]
sysroot-abi = []
