[package]
edition = "2018"
name = "ra_text_edit"
version = "0.1.0"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]
publish = false

[dependencies]
text_unit = "0.1.6"
proptest = "0.8.7"

[dev-dependencies]
test_utils = { path = "../test_utils" }
