[package]
edition = "2018"
name = "ra_proc_macro_srv"
version = "0.1.0"
authors = ["rust-analyzer developers"]
publish = false

[lib]
doctest = false

[dependencies]
ra_tt = { path = "../ra_tt" }
ra_proc_macro = { path = "../ra_proc_macro" }

serde_derive = "1.0.104"
serde = "1.0.104"
serde_json = "1.0.48"

[dev-dependencies]
cargo_metadata = "0.9.1"
difference = "2.0.0"
