[package]
edition = "2018"
name = "xtask"
version = "0.1.0"
authors = ["rust-analyzer developers"]
publish = false
license = "MIT OR Apache-2.0"

[lib]
doctest = false

[dependencies]
anyhow = "1.0.26"
flate2 = "1.0"
pico-args = "0.3.1"
proc-macro2 = "1.0.8"
quote = "1.0.2"
ungrammar = "1.1.1"
walkdir = "2.3.1"
write-json =  "0.1.0"
reqwest = { version = "0.10.7", features = ["blocking", "json"] }
graphql_client = "0.9.0"
serde = "1.0.115"
regex = "1.3.9"
chrono = "0.4.13"
