[package]
name = "libanalysis"
version = "0.1.0"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]

[dependencies]
log = "0.4.2"
failure = "0.1.2"
parking_lot = "0.6.3"
once_cell = "0.1.4"
rayon = "1.0.2"
fst = { git = "https://github.com/matklad/fst", branch = "subsequence"}
libsyntax2 = { path = "../libsyntax2" }
libeditor = { path = "../libeditor" }

[dev-dependencies]
test_utils = { path = "../test_utils" }
