[package]
name = "proc-macro-api"
version = "0.0.0"
description = "TBD"
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.65"

[lib]
doctest = false

[dependencies]
object = { version = "0.29.0", default-features = false, features = [
    "std",
    "read_core",
    "elf",
    "macho",
    "pe",
] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = { version = "1.0.81", features = ["unbounded_depth"] }
tracing = "0.1.37"
memmap2 = "0.5.4"
snap = "1.0.5"

# local deps
paths.workspace = true
tt.workspace = true
stdx.workspace = true
profile.workspace = true
# Intentionally *not* depend on anything salsa-related
# base-db.workspace = true
