[package]
name = "rustc_target"
version = "0.0.0"
edition = "2021"

[dependencies]
bitflags = "1.2.1"
tracing = "0.1"
serde_json = "1.0.59"
rustc_data_structures = { path = "../rustc_data_structures", optional = true  }
rustc_feature = { path = "../rustc_feature", optional = true }
rustc_index = { path = "../rustc_index", default-features = false }
rustc_macros = { path = "../rustc_macros", optional = true }
rustc_serialize = { path = "../rustc_serialize", optional = true  }
rustc_span = { path = "../rustc_span", optional = true }

[features]
default = ["nightly"]
nightly = [
    "rustc_data_structures",
    "rustc_feature",
    "rustc_index/nightly",
    "rustc_macros",
    "rustc_serialize",
    "rustc_span",
]