[package]
name = "mbe"
version = "0.0.0"
description = "TBD"
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.65"

[lib]
doctest = false

[dependencies]
cov-mark = "2.0.0-pre.1"
rustc-hash = "1.1.0"
smallvec = "1.10.0"
tracing = "0.1.35"

# local deps
syntax.workspace = true
parser.workspace = true
tt.workspace = true
stdx.workspace = true

[dev-dependencies]
test-utils.workspace = true
