[package]
edition = "2018"
name = "ra_ssr"
version = "0.1.0"
authors = ["rust-analyzer developers"]
license = "MIT OR Apache-2.0"
description = "Structural search and replace of Rust code"
repository = "https://github.com/rust-analyzer/rust-analyzer"

[lib]
doctest = false

[dependencies]
text_edit = { path = "../text_edit" }
syntax = { path = "../syntax" }
base_db = { path = "../base_db" }
ide_db = { path = "../ide_db" }
hir = { path = "../hir" }
rustc-hash = "1.1.0"
test_utils = { path = "../test_utils" }

[dev-dependencies]
expect = { path = "../expect" }
