[package]
name = "test_helpers"
version = "0.1.0"
authors = ["Caleb Zulawski <caleb.zulawski@gmail.com>"]
edition = "2018"
publish = false

[dependencies.proptest]
version = "0.10"
default-features = false
features = ["alloc"]
