[package]
name = "rustc_error_messages"
version = "0.0.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
rustc_serialize = { path = "../rustc_serialize" }
rustc_span = { path = "../rustc_span" }
rustc_macros = { path = "../rustc_macros" }
