[package]
name = "rustc_error_messages"
version = "0.0.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
fluent = "0.16.0"
rustc_data_structures = { path = "../rustc_data_structures" }
rustc_serialize = { path = "../rustc_serialize" }
rustc_span = { path = "../rustc_span" }
rustc_macros = { path = "../rustc_macros" }
tracing = "0.1"
unic-langid = { version = "0.9.0", features = ["macros"] }
