[package]
edition = "2018"
name = "ra_tools"
version = "0.1.0"
authors = ["rust-analyzer developers"]
publish = false

[dependencies]
walkdir = "2.1.3"
itertools = "0.8.0"
clap = "2.32.0"
quote = "1.0.2"
proc-macro2 = "1.0.1"
ron = "0.5.1"
serde = { version = "1.0.0", features = ["derive"] }
