[package]
name = "ide_helpers"
version = "0.0.0"
description = "A set of helper methods shared between various ide-level modules"
license = "MIT OR Apache-2.0"
authors = ["rust-analyzer developers"]
edition = "2018"

[lib]
doctest = false

[features]
wasm = []

[dependencies]
either = "1.6.1"
itertools = "0.9.0"

syntax = { path = "../syntax", version = "0.0.0" }
ide_db = { path = "../ide_db", version = "0.0.0" }
hir = { path = "../hir", version = "0.0.0" }
profile = { path = "../profile", version = "0.0.0" }
test_utils = { path = "../test_utils", version = "0.0.0" }
