[package]
edition = "2018"
name = "tools"
version = "0.1.0"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]
publish = false

[dependencies]
teraron = { path = "../teraron"}
walkdir = "2.1.3"
itertools = "0.7.8"
clap = "2.32.0"
failure = "0.1.1"
