[package]
name = "tools"
version = "0.1.0"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]
publish = false

[dependencies]
ron = "0.1.7"
walkdir = "2.1.3"
itertools = "0.7.8"
tera = "0.11"
clap = "2.32.0"
failure = "0.1.1"
commandspec = "0.10"
