[package]
edition = "2018"
name = "tools"
version = "0.1.0"
authors = ["rust-analyzer developers"]
publish = false

[dependencies]
teraron = "0.0.1"
walkdir = "2.1.3"
itertools = "0.8.0"
clap = "2.32.0"
failure = "0.1.4"
