[package]
name = "stdx"
version = "0.0.0"
description = "TBD"
license = "MIT OR Apache-2.0"
authors = ["rust-analyzer developers"]
edition = "2018"

[lib]
doctest = false

[dependencies]
backtrace = { version = "0.3.44", optional = true }
# Think twice before adding anything here

[features]
# Uncomment to enable for the whole crate graph
# default = [ "backtrace" ]
