[package]
name = "proc-macro-test"
version = "0.0.0"
publish = false

authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[build-dependencies]
proc-macro-test-impl = { path = "imp", version = "0.0.0" }
toolchain = { path = "../toolchain", version = "0.0.0" }
cargo_metadata = "0.15.0"
