[package]
name = "sourcegen"
version = "0.0.0"
description = "TBD"
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
xshell = "0.2.2"
