[package]
edition = "2018"
name = "ra_cli"
version = "0.1.0"
authors = ["rust-analyzer developers"]
publish = false

[dependencies]
clap = "2.32.0"
failure = "0.1.4"
join_to_string = "0.1.1"
flexi_logger = "0.10.0"
indicatif = "0.11.0"

ra_syntax = { path = "../ra_syntax" }
ra_ide_api_light = { path = "../ra_ide_api_light" }
tools = { path = "../tools" }
ra_batch = { path = "../ra_batch" }
ra_hir = { path = "../ra_hir" }
ra_db = { path = "../ra_db" }
