[package]
name = "rustc-workspace-hack"
version = "1.0.0"
license = 'MIT OR Apache-2.0'
description = """
Hack for the compiler's own build system
"""
edition = "2021"

[lib]
path = "lib.rs"

# For documentation about what this is and why in the world these dependencies
# are appearing, see `README.md`.
[dependencies]
libc = { version = "0.2", features = ["extra_traits"] }
serde_json = { version = "1.0.31", features = ["unbounded_depth"] }
# Ensure default features of regex, which are disabled in some scenarios.
regex = { version = "1.5.6" }
