[package]
name = "vfs"
version = "0.1.0"
authors = ["rust-analyzer developers"]
edition = "2018"

[dependencies]
rustc-hash = "1.0"
jod-thread = "0.1.0"
walkdir = "2.3.1"
globset = "0.4.5"
crossbeam-channel = "0.4.0"

paths = { path = "../paths" }
