[package]
edition = "2018"
name = "ra_editor"
version = "0.1.0"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]
publish = false

[dependencies]
itertools = "0.8.0"
superslice = "0.1.0"
join_to_string = "0.1.1"
rustc-hash = "1.0"

ra_syntax = { path = "../ra_syntax" }
ra_text_edit = { path = "../ra_text_edit" }

[dev-dependencies]
test_utils = { path = "../test_utils" }
proptest = "0.8.7"
