[package]
edition = "2018"
name = "ra_editor"
version = "0.1.0"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]
publish = false

[dependencies]
itertools = "0.7.8"
superslice = "0.1.0"
join_to_string = "0.1.1"
rustc-hash = "1.0"

ra_syntax = { path = "../ra_syntax" }
ra_text_edit = { path = "../ra_text_edit" }

proptest = "0.8.7"

[dev-dependencies]
test_utils = { path = "../test_utils" }
criterion = "0.2"
rand = "*"
rand_xorshift = "*"
lazy_static = "*"

[[bench]]
name = "translate_offset_with_edit_benchmark"
harness = false