[package]
edition = "2018"
name = "ra_syntax"
version = "0.1.0"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]
license = "MIT OR Apache-2.0"

[dependencies]
unicode-xid = "0.1.0"
itertools = "0.7.8"
drop_bomb = "0.1.4"
parking_lot = "0.6.0"
rowan = "0.1.1"

[dev-dependencies]
test_utils = { path = "../test_utils" }
walkdir = "2.2.0"
