[package]
edition = "2018"
name = "ra_syntax"
version = "0.1.0"
authors = ["rust-analyzer developers"]
license = "MIT OR Apache-2.0"
description = "Comment and whitespace preserving parser for the Rust langauge"
repository = "https://github.com/rust-analyzer/rust-analyzer"

[dependencies]
itertools = "0.8.0"
rowan = "0.6.1"
rustc_lexer = "0.1.0"
rustc-hash = "1.0.1"
arrayvec = "0.4.10"
once_cell = "1.2.0"

ra_text_edit = { path = "../ra_text_edit" }
ra_parser = { path = "../ra_parser" }

[dev-dependencies]
test_utils = { path = "../test_utils" }
walkdir = "2.2.0"
