[package]
name = "libsyntax2"
version = "0.1.0"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]
license = "MIT OR Apache-2.0"

[dependencies]
unicode-xid = "0.1.0"
text_unit = "0.1.2"
itertools = "0.7.5"
drop_bomb = "0.1.4"
parking_lot = "0.6.0"

[dev-dependencies]
assert_eq_text = { path = "../assert_eq_text" }
