[package]
edition = "2018"
name = "gen_lsp_server"
version = "0.1.0"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]
repository = "https://github.com/rust-analyzer/rust-analyzer"
license = "MIT OR Apache-2.0"
description = "Generic LSP server scaffold."

[dependencies]
languageserver-types = "0.53.0"
log = "0.4.3"
failure = "0.1.2"
serde_json = "1.0.24"
serde = "1.0.71"
crossbeam-channel = "0.2.4"
