[package]
name = "m"
version = "0.1.0"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]

[dependencies]
relative-path = "0.3.7"
failure = "0.1.2"
serde_json = "1.0.24"
serde = "1.0.71"
serde_derive = "1.0.71"
drop_bomb = "0.1.0"
crossbeam-channel = "0.2.4"
threadpool = "1.7.1"
flexi_logger = "0.9.1"
log = "0.4.3"
url_serde = "0.2.0"
languageserver-types = "0.49.0"
walkdir = "2.2.0"
im = { version = "11.0.1", features = ["arc"] }
text_unit = { version = "0.1.2", features = ["serde"] }

libsyntax2 = { path = "../libsyntax2" }
libeditor = { path = "../libeditor" }
libanalysis = { path = "../libanalysis" }
gen_lsp_server = { path = "../gen_lsp_server" }

[dev-dependencies]
tempdir = "0.3.7"
