[package]
name = "ide-assists"
version = "0.0.0"
description = "TBD"

authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
cov-mark = "2.0.0-pre.1"

itertools = "0.10.5"
either = "1.7.0"
smallvec = "1.10.0"

stdx = { path = "../stdx", version = "0.0.0" }
syntax = { path = "../syntax", version = "0.0.0" }
text-edit = { path = "../text-edit", version = "0.0.0" }
profile = { path = "../profile", version = "0.0.0" }
ide-db = { path = "../ide-db", version = "0.0.0" }
hir = { path = "../hir", version = "0.0.0" }

[dev-dependencies]
test-utils = { path = "../test-utils" }
sourcegen = { path = "../sourcegen" }
expect-test = "1.4.0"

[features]
in-rust-tree = []
