[package]
edition = "2018"
name = "ra_assists"
version = "0.1.0"
authors = ["rust-analyzer developers"]
license = "MIT OR Apache-2.0"

[lib]
doctest = false

[dependencies]
rustc-hash = "1.1.0"
itertools = "0.9.0"
either = "1.5.3"

stdx = { path = "../stdx" }

syntax = { path = "../syntax" }
text_edit = { path = "../text_edit" }
profile = { path = "../profile" }
base_db = { path = "../base_db" }
ide_db = { path = "../ide_db" }
hir = { path = "../hir" }
test_utils = { path = "../test_utils" }
