name: Security audit
on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * 1' # every monday at 10:00 UTC
permissions:
  issues: write
  checks: write
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rustsec/audit-check@v1.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
