name: release
on:
  schedule:
  - cron: '0 0 * * *' # midnight UTC

  push:
    branches:
    - release
    - trigger-nightly

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTFLAGS: "-D warnings -W unreachable-pub"
  RUSTUP_MAX_RETRIES: 10

jobs:
  dist-windows:
    name: dist (Windows)
    runs-on: windows-latest
    env:
      RA_TARGET: x86_64-pc-windows-msvc

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # We need to disable the existing toolchain to avoid updating rust-docs
    # which takes a long time. The fastest way to do this is to rename the
    # existing folder, as deleting it takes about as much time as not doing
    # anything and just updating rust-docs.
    - name: Rename existing rust toolchain
      run: Rename-Item C:\Users\runneradmin\.rustup\toolchains\stable-x86_64-pc-windows-msvc C:\Users\runneradmin\.rustup\toolchains\stable-x86_64-pc-windows-msvc.old

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Dist
      run: cargo xtask dist

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: dist-windows-latest
        path: ./dist

  dist-ubuntu:
    name: dist (Ubuntu 16.04)
    runs-on: ubuntu-16.04
    env:
      RA_TARGET: x86_64-unknown-linux-gnu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Install Nodejs
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Dist
      if: github.ref == 'refs/heads/release'
      run: cargo xtask dist --client 0.2.$GITHUB_RUN_NUMBER

    - name: Dist
      if: github.ref != 'refs/heads/release'
      run: cargo xtask dist --nightly --client 0.3.$GITHUB_RUN_NUMBER-nightly

    - name: Nightly analysis-stats check
      if: github.ref != 'refs/heads/release'
      run: target/${{ env.RA_TARGET }}/release/rust-analyzer analysis-stats .

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: dist-ubuntu-16.04
        path: ./dist

  dist-macos-latest:
    name: dist (MacOS latest)
    runs-on: macos-latest
    env:
      RA_TARGET: x86_64-apple-darwin

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Dist
      run: cargo xtask dist

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: dist-macos-latest
        path: ./dist

  dist-macos-11:
    name: dist (MacOS 11.0)
    runs-on: macos-11.0
    env:
      RA_TARGET: aarch64-apple-darwin

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Rust toolchain (beta)
      uses: actions-rs/toolchain@v1
      with:
        toolchain: beta
        target: aarch64-apple-darwin
        profile: minimal
        override: true

    - name: Dist
      run: cargo xtask dist

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: dist-macos-11.0
        path: ./dist

  publish:
    name: publish
    runs-on: ubuntu-16.04
    needs: ['dist-windows', 'dist-ubuntu', 'dist-macos-latest', 'dist-macos-11']
    steps:
    - name: Install Nodejs
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - run: echo "TAG=$(date --iso --utc)" >> $GITHUB_ENV
      if: github.ref == 'refs/heads/release'
    - run: echo "TAG=nightly" >> $GITHUB_ENV
      if: github.ref != 'refs/heads/release'
    - run: 'echo "TAG: $TAG"'

    - name: Checkout repository
      uses: actions/checkout@v2

    - run: echo "HEAD_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
    - run: 'echo "HEAD_SHA: $HEAD_SHA"'

    - uses: actions/download-artifact@v1
      with:
        name: dist-macos-11.0
        path: dist
    - uses: actions/download-artifact@v1
      with:
        name: dist-macos-latest
        path: dist
    - uses: actions/download-artifact@v1
      with:
        name: dist-ubuntu-16.04
        path: dist
    - uses: actions/download-artifact@v1
      with:
        name: dist-windows-latest
        path: dist
    - run: ls -al ./dist

    - name: Publish Release
      uses: ./.github/actions/github-release
      with:
        files: "dist/*"
        name: ${{ env.TAG }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - run: npm ci
      working-directory: ./editors/code

    - name: Publish Extension
      if: github.ref == 'refs/heads/release'
      working-directory: ./editors/code
      # token from https://dev.azure.com/rust-analyzer/
      run: npx vsce publish --pat ${{ secrets.MARKETPLACE_TOKEN }} --packagePath ../../dist/rust-analyzer.vsix
