name: Various rustc tests

on:
  - push

jobs:
  bootstrap_rustc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache cargo target dir
      uses: actions/cache@v3
      with:
        path: build/cg_clif
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('rust-toolchain', '**/Cargo.lock') }}

    - name: Use sparse cargo registry
      run: |
        cat >> ~/.cargo/config.toml <<EOF
        [unstable]
        sparse-registry = true
        EOF

    - name: Prepare dependencies
      run: |
        git config --global user.email "user@example.com"
        git config --global user.name "User"
        ./y.rs prepare

    - name: Test
      run: ./scripts/test_bootstrap.sh
  rustc_test_suite:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache cargo target dir
      uses: actions/cache@v3
      with:
        path: build/cg_clif
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('rust-toolchain', '**/Cargo.lock') }}

    - name: Use sparse cargo registry
      run: |
        cat >> ~/.cargo/config.toml <<EOF
        [unstable]
        sparse-registry = true
        EOF

    - name: Prepare dependencies
      run: |
        git config --global user.email "user@example.com"
        git config --global user.name "User"
        ./y.rs prepare

    - name: Test
      run: ./scripts/test_rustc_tests.sh
