[package]
name = "limit"
version = "0.0.0"
description = "TBD"
license = "MIT OR Apache-2.0"
authors = ["rust-analyzer developers"]
edition = "2021"
rust-version = "1.56"

[features]
tracking = []
default = ["tracking"]
